// categoriesWhitelist.js
const TECH_SECURITY_GAMING_CATEGORIES = [
    "routers",
    "wifi hotspot",
    "fiber router",
    "network accessories",
    "network switch",
    "access point",
    "cables",
    "laptops",
    "computers",
    "computer gadgets",
    "computer accessories",
    "monitors",
    "printers",
    "storage",
    "ssd",
    "hdd",
    "flash disk",
    "keyboard",
    "mouse",
    "headsets",
    "playstation",
    "ps4",
    "ps5",
    "gaming console",
    "gaming pad",
    "gaming accessories",
    "cctv",
    "security camera",
    "ip camera",
    "security gadgets",
    "surveillance",
];

module.exports = TECH_SECURITY_GAMING_CATEGORIES;
