
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  node_modules:

